// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: event.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
  name, date, location, capacity
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, created_at, updated_at, deleted_at, name, date, location, capacity, seats
`

type CreateEventParams struct {
	Name     pgtype.Text      `json:"name"`
	Date     pgtype.Timestamp `json:"date"`
	Location pgtype.Text      `json:"location"`
	Capacity pgtype.Int4      `json:"capacity"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.Date,
		arg.Location,
		arg.Capacity,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Date,
		&i.Location,
		&i.Capacity,
		&i.Seats,
	)
	return i, err
}
