// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int32            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	Name      pgtype.Text      `json:"name"`
	Date      pgtype.Timestamp `json:"date"`
	Location  pgtype.Text      `json:"location"`
	Capacity  pgtype.Int4      `json:"capacity"`
	Seats     []byte           `json:"seats"`
}

type Price struct {
	ID        int32            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	Class     pgtype.Text      `json:"class"`
	Price     pgtype.Float8    `json:"price"`
	Event     pgtype.Int4      `json:"event"`
}
