// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Event struct {
	ID        int64                 `json:"id"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt sql.NullTime          `json:"updated_at"`
	DeletedAt sql.NullTime          `json:"deleted_at"`
	Name      string                `json:"name"`
	Date      sql.NullTime          `json:"date"`
	Location  string                `json:"location"`
	Capacity  int32                 `json:"capacity"`
	Seats     pqtype.NullRawMessage `json:"seats"`
}

type Price struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Class     string       `json:"class"`
	Price     float64      `json:"price"`
	Event     int32        `json:"event"`
}
